### ISSUE TITLE
is possible to list Magento versiones?

### ISSUE THREAD

**Issue by amarroni** [sandermangel/awesome-pwa-ecommerce#4]
@sandermangel excellent page!

As I mentioned in the subject, could be possible know the Magento version?

Best,
Alejandro.

**Comment by sandermangel** [comment]
Hi @amarroni with PWA it is quite a challenge to figure out the exact system behind it, even more so the version. I'm not sure if this is attainable but you are welcome to make a PR for any case you know the version of.

**Comment by amarroni** [comment]
Sound like a plan to me!
Hope I can help you.

closing the issue.

Best,
Alejandro.
